=== GossJS/15092017-LitvinovKV/Part2/xml-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:simpleType name="stringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:complexType name="markType">
		<!-- расширение для сложного типа без элементов -->
		<xs:simpleContent>
			<!-- расширяет элемент simpleType или complexType --> 
			<xs:extension base="xs:integer">
				<xs:attribute name="discipline" type="stringType" use="required"/>
			</xs:extension>
		</xs:simpleContent>			
	</xs:complexType>

	<xs:complexType name="studentType">
		<xs:sequence>
			<xs:element name="mark" maxOccurs="unbounded" type="markType"/>
		</xs:sequence>
		<xs:attribute name="name" type="stringType" use="required"/>
	</xs:complexType>

	<xs:complexType name="tableType">
		<xs:sequence>
			<xs:element name="student" maxOccurs="unbounded" type="studentType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="table" type="tableType"/>

</xs:schema>

=== GossJS/15092017-LitvinovKV/Part2/general.xml
<?xml version="1.0" encoding="UTF-8"?>

<table 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xml-schema.xsd">
	<student name="Иванов">
		<mark discipline="Мультимедиа">3</mark>
		<mark discipline="Веб-дизайн">3</mark>
		<mark discipline="Графика">5</mark>
	</student>
	<student name="Петрова">
		<mark discipline="Мультимедиа">3</mark>
		<mark discipline="Веб-дизайн">4</mark>
		<mark discipline="Графика">5</mark>
		<mark discipline="Логина">5</mark>
	</student>
	<student name="Сидоренко">
		<mark discipline="Мультимедиа">3</mark>
		<mark discipline="Веб-дизайн">3</mark>
		<mark discipline="Графика">5</mark>
		<mark discipline="Логина">4</mark>
	</student>
</table>
